#!/bin/sh

# --- Variables ---
polybar_config="$HOME/.config/polybar/polybar.ini"
wallpaper="/usr/share/backgrounds/wallpaper-2.jpg"

# Key repeat settings
repeat_rate=200
delay=65

# --- Monitors ---

# Set up monitors with xrandr based on monitors
if xrandr | grep -q "HDMI-0 connected"; then
    xrandr --output HDMI-0 --primary --mode 1920x1080 --pos 1366x0 --rotate normal \
           --output DP-0 --mode 1366x768 --pos 0x312 --rotate normal \
           --output eDP-1-0 --mode 1920x1200 --pos 0x1080 --rotate normal
    sleep 1
    bspc monitor eDP-1-0 -d 1
    bspc monitor DP-0 -d 2
    bspc monitor HDMI-0 -d 3 4 5 6 7 8
else
    xrandr --output eDP --primary --mode 1920x1200 --pos 0x0

    bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 0
fi

# --- Initialization ---
pgrep -x sxhkd > /dev/null || sxhkd &        # Keybinds Manager
picom &                                      # Compositor
feh --bg-scale $wallpaper &                  # Set wallpaper
polybar --config=$polybar_config main -r &   # Launch panel
ulauncher &                                  # Launch ULauncher
setxkbmap -option caps:swapescape &          # Swap Caps Lock and Escape
xset r rate $repeat_rate $delay &            # Set key repeat rate

# --- bspwm Configuration ---

# Window Rules
bspc rule -a pavucontrol state=floating border=off
bspc rule -a Ulauncher state=floating border=off

# Window Borders
bspc config border_width         2
bspc config window_gap          3

# Border Colors
bspc config focused_border_color "#bb9af7ff"

bspc config normal_border_color  "#4C566A"


# --- Keybindings ---

